### ISSUE TITLE
The iOS version is crashing when the picture is taken.

### ISSUE THREAD

**Issue by jreyes13** [SpaceTecPartners/EGNSS4CAP#3] opened 2021-04-10 17:57 UTC
After pressing the button and once the position is being calculated, the application is crashing and not picture is taken (not all the times).

**Comment by SpaceTecPartners** [comment] 2021-04-29 12:07
scheduled for fix

**Comment by SpaceTecPartners** [comment] 2021-05-13 08:18
found a root cause and fixed in rel 2.2

**Closed by SpaceTecPartners** 2021-05-13 08:18 UTC
Labels: bug
